# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171017_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_signatures',
            field=models.BooleanField(default=True, verbose_name='Показывать подпись'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Подпись на форуме'),
        ),
    ]
