# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191028_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_emails',
            field=models.BooleanField(default=True),
        ),
    ]
