# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creation', models.DateTimeField(default=None, null=True, verbose_name='Дата создания')),
                ('text', models.CharField(default=None, max_length=1024, null=True)),
                ('text_type', models.CharField(choices=[('ssml', 'ssml'), ('text', 'text')], default=None, max_length=4, null=True)),
                ('language_code', models.CharField(choices=[('fr-FR', 'French'), ('ru-RU', 'Russian')], default=None, max_length=16, null=True)),
                ('output_format', models.CharField(choices=[('json', 'json'), ('mp3', 'mp3'), ('ogg_vorbis', 'ogg_vorbis'), ('pcm', 'pcm')], default=None, max_length=16, null=True)),
                ('sample_rate', models.CharField(choices=[('8000', '8000'), ('16000', '16000'), ('22050', '22050')], default=None, max_length=16, null=True)),
                ('voice_id', models.CharField(choices=[('Lea', 'lea'), ('Celine', 'celine'), ('Mathieu', 'matthieu'), ('Maxim', 'maxim'), ('Tatyana', 'tatyana')], default=None, max_length=16, null=True)),
                ('task_id', models.CharField(default=None, max_length=64, null=True)),
                ('task_status', models.CharField(choices=[('scheduled', 'scheduled'), ('inProgress', 'inProgress'), ('completed', 'completed'), ('failed', 'failed')], default=None, max_length=16, null=True)),
                ('request_characters', models.IntegerField(default=None, null=True)),
                ('url', models.URLField(default=None, null=True, verbose_name='Ссылка на файл')),
                ('error', models.BooleanField(default=False)),
            ],
        ),
    ]
