# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollytask',
            name='engine',
            field=models.CharField(choices=[('standard', 'Standard'), ('neural', 'Neural'), ('long-form', 'Long form'), ('generative', 'Generative')], default='neural', max_length=16),
        ),
    ]
