# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0002_pollytask_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollytask',
            name='stream',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pollytask',
            name='voice_id',
            field=models.CharField(choices=[('Lea', 'lea'), ('Remi', 'remi'), ('Celine', 'celine'), ('Mathieu', 'matthieu'), ('Maxim', 'maxim'), ('Tatyana', 'tatyana')], default=None, max_length=16, null=True),
        ),
    ]
