ITEMS = {
	1: dict(
		name='Добровольное пожертвование в поддержку проекта 68р',
		description='le-francais.ru — Покупка 1 виртуальной чашечки кофе',
		category='coffee_cups',
		order_type_id=1,
		quantity=1,
		price=6800,
		site_quantity=1,
	),
	2: dict(
		name='Добровольное пожертвование в поддержку проекта 295р',
		description='le-francais.ru — Покупка 5 виртуальных чашечек кофе',
		category='coffee_cups',
		order_type_id=1,
		quantity=1,
		price=29500,
		site_quantity=5,
	),
	3: dict(
		name='Добровольное пожертвование в поддержку проекта 490р',
		description='le-francais.ru — Покупка 10 виртуальных чашечек кофе',
		category='coffee_cups',
		order_type_id=1,
		quantity=1,
		price=49000,
		site_quantity=10,
	),
	4: dict(
		name='Добровольное пожертвование в поддержку проекта 780р',
		description='le-francais.ru — Покупка 20 виртуальных чашечек кофе',
		category='coffee_cups',
		order_type_id=1,
		quantity=1,
		price=78000,
		site_quantity=20,
	),
	5: dict(
		name='Добровольное пожертвование в поддержку проекта 1690р',
		description='le-francais.ru — Покупка 50 виртуальных чашечек кофе',
		category='coffee_cups',
		order_type_id=1,
		quantity=1,
		price=169000,
		site_quantity=50,
	),
	6: dict(
		name='1 активация (доступ к материалам уроков)',
		description='Доступ к материалам урока французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=6800,
		site_quantity=1,
	),
	7: dict(
		name='Абонемент на 5 активаций (доступ к материалам уроков)',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=29500,
		site_quantity=5,
	),
	8: dict(
		name='Абонемент на 10 активаций (доступ к материалам уроков)',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=49000,
		site_quantity=10,
	),
	9: dict(
		name='Абонемент на 20 активаций (доступ к материалам уроков)',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=78000,
		site_quantity=20,
	),
	10: dict(
		name='Абонемент на 50 активаций (доступ к материалам уроков)',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=169000,
		site_quantity=50,
	),
	11: dict(
		name='1 активация со скидкой (доступ к материалам уроков)',
		description='Доступ к материалам урока французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=3900,
		site_quantity=1,
	),
	12: dict(
		name='Абонемент на 5 активаций со скидкой (доступ к материалам уроков)',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=19500,
		site_quantity=5,
	),
	13: dict(
		name='Абонемент на доступ к материалам 10 уроков со скидкой',
		description='Покупка абонемента на доступ к материалам уроков французского языка',
		category='tickets',
		order_type_id=1,
		quantity=1,
		price=39000,
		site_quantity=10,
	),
}

CUPS_IDS = [1, 2, 3, 4, 5]
