# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-29 07:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

from ads.models import DEFAULT_PLACEMENTS_CHOICES


def forward_func(apps, schema_editor):
    Placement = apps.get_model('ads', 'Placement')
    db_alias = schema_editor.connection.alias
    Placement.objects.using(db_alias).bulk_create(
        Placement(name=name, code=code) for code, name in DEFAULT_PLACEMENTS_CHOICES
    )

def reverse_func(apps, schema_editor):
    Placement = apps.get_model('ads', 'Placement')
    db_alias = schema_editor.connection.alias
    codes = [code for code, name in DEFAULT_PLACEMENTS_CHOICES]
    Placement.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('redirect_url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_url', models.URLField(blank=True)),
                ('disable', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ad_units', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of AdUnit names.', size=None)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='placements',
            field=models.ManyToManyField(blank=True, to='ads.Placement'),
        ),
        migrations.AddField(
            model_name='creative',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', related_query_name='creative', to='ads.LineItem'),
        ),
        migrations.RunPython(
            forward_func, reverse_func
        )
    ]
