# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 15:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# ads.migrations.0001_initial
from ads.models import DEFAULT_PLACEMENTS_CHOICES


def forward_func(apps, schema_editor):
    Placement = apps.get_model('ads', 'Placement')
    db_alias = schema_editor.connection.alias
    Placement.objects.using(db_alias).bulk_create(
        Placement(name=name, code=code) for code, name in DEFAULT_PLACEMENTS_CHOICES
    )

def reverse_func(apps, schema_editor):
    Placement = apps.get_model('ads', 'Placement')
    db_alias = schema_editor.connection.alias
    codes = [code for code, name in DEFAULT_PLACEMENTS_CHOICES]
    Placement.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    replaces = [('ads', '0001_initial'), ('ads', '0002_auto_20211108_1633'), ('ads', '0003_auto_20211108_1851'), ('ads', '0004_auto_20211109_1431')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('redirect_url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_url', models.URLField(blank=True)),
                ('disable', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ad_units', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of AdUnit names.', size=None)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='placements',
            field=models.ManyToManyField(blank=True, to='ads.Placement'),
        ),
        migrations.AddField(
            model_name='creative',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', related_query_name='creative', to='ads.LineItem'),
        ),
        migrations.RunPython(
            code=forward_func,
            reverse_code=reverse_func,
        ),
        migrations.RenameField(
            model_name='creative',
            old_name='redirect_url',
            new_name='click_through_url',
        ),
        migrations.AddField(
            model_name='creative',
            name='_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='do_not_show_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список slug'ов страниц через запятую", size=None, verbose_name='Do not show if user was on following pages'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='capping_day',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='capping_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='capping_week',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
