# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_squashed_0004_auto_20211109_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
