# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-08 13:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='redirect_url',
            new_name='click_through_url',
        ),
        migrations.AddField(
            model_name='creative',
            name='width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='do_not_show_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список slug'ов страниц через запятую", size=None, verbose_name='Do not show if user was on following pages'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
