# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20211109_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='do_not_show_if_was_on_conjugations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creative',
            name='image_url',
            field=models.URLField(blank=True, help_text='Одно из полей image или image_url должно быть заполнено'),
        ),
    ]
