# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20211108_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='capping_day',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='capping_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='capping_week',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
