# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20211108_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='width',
            new_name='_width',
        ),
        migrations.AddField(
            model_name='creative',
            name='_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
