# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20211110_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='do_not_display_to_registered_users',
            field=models.BooleanField(default=True),
        ),
    ]
