# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 15:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_lineitem_do_not_display_to_registered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='do_not_show_if_was_on_conjugations',
            field=models.BooleanField(default=False, verbose_name="Don't display if user had visited conjugations pages"),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='do_not_show_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список slug'ов страниц через запятую", size=None, verbose_name="Don't display if user had visited following pages"),
        ),
    ]
