# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_creative_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='html',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
