# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20220425_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='fluid',
            field=models.BooleanField(default=False),
        ),
    ]
