# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_creative_fluid_squashed_0019_auto_20221027_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
