# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_creative_fluid'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
