# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-13 13:03
from __future__ import unicode_literals

from django.db import migrations

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('ads', 'Creative')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_creative_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
