# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-13 13:03
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   unique=True),
        ),
    ]
