# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-01 13:26
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20221031_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='image',
            field=models.ImageField(blank=True, upload_to=ads.models.creative_image_file_update),
        ),
    ]
