# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20221101_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='Will override line item values', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Will override line item values', max_length=256, null=True),
        ),
    ]
