# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-01 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0013_remove_uuid_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('view', 'View'), ('click', 'Click')], max_length=10)),
                ('creative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.Creative')),
                ('line_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.LineItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
