# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='targeting_city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='targeting_country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
