# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20220602_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='click_through_url',
        ),
        migrations.AddField(
            model_name='creative',
            name='image_click_through_url',
            field=models.URLField(blank=True),
        ),
    ]
