# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_log_ad_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='targeting_invert',
            field=models.BooleanField(default=False),
        ),
    ]
