# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-09 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_lineitem_targeting_invert'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ad_unit_placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
