# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_log_ad_unit_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='click_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
