# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-10 14:30
from __future__ import unicode_literals

import ads.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20221109_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='utm_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=ads.models.set_default_utm),
        ),
    ]
