# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-27 14:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

def forward_func(apps, schema_editor):
    LineItem = apps.get_model('ads', 'LineItem')
    db_alias = schema_editor.connection.alias
    LineItem.objects.using(db_alias).filter(labels__isnull=True).update(labels=[])

def backward_func(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20221027_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.RunPython(forward_func, backward_func)
    ]
