# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-07 16:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_lineitem_placements_inverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='do_not_display_to_anonymous_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='do_not_display_to_donating_users',
            field=models.BooleanField(default=False, verbose_name='Do not display to users who ever donate'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='do_not_display_to_donating_users_days_ago',
            field=models.IntegerField(blank=True, null=True, verbose_name='Do not display to users, who donate less than N days age'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='less_than_n_days_ago',
            field=models.BooleanField(default=False, verbose_name='Не показывать пользователям, видевших следующие страницы менее чем N дней назад'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='less_than_n_days_ago_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение в днях'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='do_not_show_if_was_on_conjugations',
            field=models.BooleanField(default=False, verbose_name="Don't display if user visited conjugations pages"),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='do_not_show_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Список slug'ов страниц через запятую", size=None, verbose_name="Don't display if user visited following pages"),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='placements_inverted',
            field=models.BooleanField(default=False, verbose_name='Invert Placements'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='targeting_invert',
            field=models.BooleanField(default=False, verbose_name='Invert Geo Targeting'),
        ),
    ]
