# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_auto_20221207_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='iframe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creative',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Will override ad unit value', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
