# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-16 12:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_auto_20221214_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='targeting_cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='targeting_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
