# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_auto_20221216_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
