# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-29 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_creative_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='targeting_cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None, verbose_name='List of cities'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='targeting_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None, verbose_name='List of countries'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='targeting_invert',
            field=models.BooleanField(default=False, verbose_name='Location targeting work as exclusion'),
        ),
    ]
