# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_auto_20221229_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='capping_status_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='capping_status_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='capping_status_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
