# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-29 15:06
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pybb', '0014_topic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoNotificationsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('topic', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_notifications', to='pybb.Topic')),
            ],
        ),
    ]
