# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-10-06 23:33
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybb', '0014_topic_description'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_reply', models.BooleanField(default=True, help_text='Уведомлять по электронной почте, когда кто-то отвечает на ваше сообщение или цитирует его.', verbose_name='Присылать email при ответе на мое сообщение или цитировании')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений форума',
                'verbose_name_plural': 'Настройки уведомлений форума',
            },
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_info', to='pybb.Post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='pybb.Post')),
            ],
            options={
                'verbose_name': 'Ответ на сообщение',
                'verbose_name_plural': 'Ответы на сообщения',
            },
        ),
    ]
