# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-10-07 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_likes(apps, schema_editor):
    Like = apps.get_model('pybb', 'Like')
    PostReaction = apps.get_model('forum', 'PostReaction')

    likes = Like.objects.filter(active=True).select_related('profile')
    reactions_to_create = []
    seen = set()
    for like in likes.iterator():
        if not like.profile_id or not like.post_id:
            continue
        user_id = like.profile.user_id
        key = (like.post_id, user_id)
        if key in seen:
            continue
        seen.add(key)
        reactions_to_create.append(
            PostReaction(
                post_id=like.post_id,
                user_id=user_id,
                reaction_type='heart',
                active=True,
                created=like.created,
            )
        )
        if len(reactions_to_create) >= 2000:
            PostReaction.objects.bulk_create(reactions_to_create)
            reactions_to_create = []
    if reactions_to_create:
        PostReaction.objects.bulk_create(reactions_to_create)


def reverse_migrate_likes(apps, schema_editor):
    PostReaction = apps.get_model('forum', 'PostReaction')
    PostReaction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybb', '0014_topic_description'),
        ('forum', '0002_forumuserpreference_postreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(default='heart', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pybb.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реакция на сообщение',
                'verbose_name_plural': 'Реакции на сообщения',
            },
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set([('post', 'user')]),
        ),
        migrations.RunPython(migrate_existing_likes, reverse_migrate_likes),
    ]

