# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20170907_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email adress already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
