# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 10:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_usedusernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_usernames',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
