# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_user_used_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
