# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_user_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='must_pay',
        ),
    ]
