# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_userlesson'),
        ('custom_user', '0012_auto_20180823_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payed_lessons',
            field=models.ManyToManyField(related_name='paid_users', through='home.UserLesson', to='home.LessonPage'),
        ),
    ]
