# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0014_user_cup_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saw_message',
            field=models.BooleanField(default=False),
        ),
    ]
