# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0015_user_saw_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_cup_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_cup_credit',
            field=models.IntegerField(default=0),
        ),
    ]
