# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0016_auto_20181205_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_cup_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_cup_credit',
        ),
    ]
