# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0017_auto_20181205_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cup_amount',
            new_name='_cup_amount',
        ),
        migrations.AddField(
            model_name='user',
            name='_cup_credit',
            field=models.IntegerField(default=0),
        ),
    ]
