# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0018_auto_20181205_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_low_price',
            field=models.BooleanField(default=0),
        ),
    ]
