# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0019_user__low_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_pay',
            field=models.BooleanField(default=True),
        ),
    ]
