# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0023_user_push4site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='push4site',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='push4site ids'),
        ),
    ]
