# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0024_auto_20190531_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
