# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0025_auto_20190625_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
