# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0026_auto_20190626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recaptcha3_score',
            field=models.FloatField(null=True),
        ),
    ]
