# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0027_user_recaptcha3_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_tickets',
            field=models.NullBooleanField(),
        ),
    ]
