# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0028_user_show_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=32, null=True, verbose_name='timezone'),
        ),
    ]
