# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0028_user_show_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='type',
            field=models.IntegerField(choices=[(1, 'Listened Lesson'), (2, 'Downloaded Lesson')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='value',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
