# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0030_logmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='type',
            field=models.IntegerField(choices=[(1, 'Download'), (2, 'listen')], null=True),
        ),
    ]
