# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0031_auto_20200129_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='type',
            field=models.IntegerField(choices=[(2, 'Download'), (1, 'listen')], null=True),
        ),
    ]
