# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0032_auto_20200220_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
