# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0033_logmessage_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_for_emails',
            field=models.CharField(blank=True, default=None, help_text='Name, which will be used in emails instead of username', max_length=32, null=True),
        ),
    ]
