# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0034_user_name_for_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=True),
        ),
    ]
