# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-04 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0036_auto_20220328_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
