# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0037_auto_20241204_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_donated',
            field=models.BooleanField(default=False, verbose_name='has donated'),
        ),
    ]
