# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='draft_title',
        ),
    ]
