LAYOUT_EN = '''`~!@#$%^&qwertyuiop[]asdfghjkl;'zxcvbnm,./QWERTYUIOP{}ASDFGHJKL:"|ZXCVBNM<>?'''
LAYOUT_RU = '''ёЁ!"№;%:?йцукенгшщзхъфывапролджэячсмитьбю.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭ/ЯЧСМИТЬБЮ,'''
FREQUENT_URLS = [
	'''<a href="/conjugaison/etre">être</a>''',
	'''<a href="/conjugaison/avoir">avoir</a>''',
	'''<a href="/conjugaison/faire">faire</a>''',
	'''<a href="/conjugaison/dire">dire</a>''',
	'''<a href="/conjugaison/pouvoir">pouvoir</a>''',
	'''<a href="/conjugaison/aller">aller</a>''',
	'''<a href="/conjugaison/voir">voir</a>''',
	'''<a href="/conjugaison/vouloir">vouloir</a>''',
	'''<a href="/conjugaison/venir">venir</a>''',
	'''<a href="/conjugaison/devoir">devoir</a>''',
	'''<a href="/conjugaison/prendre">prendre</a>''',
	'''<a href="/conjugaison/trouver">trouver</a>''',
	'''<a href="/conjugaison/donner">donner</a>''',
	'''<a href="/conjugaison/falloir">falloir</a>''',
	'''<a href="/conjugaison/parler">parler</a>''',
	'''<a href="/conjugaison/mettre">mettre</a>''',
	'''<a href="/conjugaison/savoir">savoir</a>''',
	'''<a href="/conjugaison/passer">passer</a>''',
	'''<a href="/conjugaison/regarder">regarder</a>''',
	'''<a href="/conjugaison/aimer">aimer</a>''',
	'''<a href="/conjugaison/croire">croire</a>''',
	'''<a href="/conjugaison/demander">demander</a>''',
	'''<a href="/conjugaison/rester">rester</a>''',
	'''<a href="/conjugaison/repondre">répondre</a>''',
	'''<a href="/conjugaison/entendre">entendre</a>''',
	'''<a href="/conjugaison/penser">penser</a>''',
	'''<a href="/conjugaison/arriver">arriver</a>''',
	'''<a href="/conjugaison/connaitre">connaître</a>''',
	'''<a href="/conjugaison/devenir">devenir</a>''',
	'''<a href="/conjugaison/sentir">sentir</a>''',
	'''<a href="/conjugaison/sembler">sembler</a>''',
	'''<a href="/conjugaison/tenir">tenir</a>''',
	'''<a href="/conjugaison/comprendre">comprendre</a>''',
	'''<a href="/conjugaison/rendre">rendre</a>''',
	'''<a href="/conjugaison/attendre">attendre</a>''',
	'''<a href="/conjugaison/sortir">sortir</a>''',
	'''<a href="/conjugaison/vivre">vivre</a>''',
	'''<a href="/conjugaison/reprendre">reprendre</a>''',
	'''<a href="/conjugaison/entrer">entrer</a>''',
	'''<a href="/conjugaison/porter">porter</a>''',
	'''<a href="/conjugaison/chercher">chercher</a>''',
	'''<a href="/conjugaison/revenir">revenir</a>''',
	'''<a href="/conjugaison/appeler">appeler</a>''',
]
VOWELS_LIST = ['a', 'ê', 'é', 'h', 'e', 'â', 'i', 'o', 'ô', 'u', 'w', 'y',
               'œ', ]

POLLY_EMPTY_MOOD_NAMES = [
	('indicative', 'composé-past'),
	('indicative', 'pluperfect'),
	('indicative', 'simple-past'),
	('indicative', 'antérieur-past'),
	('indicative', 'future'),
	('indicative', 'antérieur-future'),
]

MOODS = [
	('infinitive', "Infinitif"),
	('indicative', "Indicatif"),
	('subjunctive', "Subjonctif"),
	('conditional', "Conditionnel"),
	('imperative', "Impératif"),
	('participle', "Participe"),
	('gerund', "Gérondif"),
]


TENSES = [
	('infinitive-present', 'présent'),
	('present', "présent"),
	('past', "passé"),
	('composé-past', "passé composé"),
	('imperfect', "imparfait"),
	('pluperfect', "plus que parfait"),
	('future', "futur simple"),
	('simple-past', "passé simple"),
	('antérieur-future', "futur antérieur"),
	('antérieur-past', "passé antérieur"),
	('past-first', "passé"),
	('past-second', "passé deuxième forme"),
	('imperative-present', 'présent'),
	('present-participle', 'présent'),
	('past-participle', 'passé'),
]
PERSONS = [
    (0, 'форма \u00abя\u00bb'),
    (1, 'форма \u00abты\u00bb'),
    (2, 'форма \u00abон\u00bb'),
    (3, 'форма \u00abмы\u00bb'),
    (4, 'форма \u00abвы\u00bb'),
    (5, 'форма \u00abони\u00bb'),
]
TEMPLATE_NAME = {
    'indicative': "Indicatif",
    'present': "Présent",
    'imperfect': "Imparfait",
    'simple-past': "Passé simple",
    'future': "Futur simple",
    'composé-past': "Passé composé",
    'pluperfect': "Plus que parfait",
    'antérieur-past': "Passé antérieur",
    'antérieur-future': "Futur antérieur",
    'subjunctive': "Subjonctif",
    'past': "Passé",
    'conditional': "Conditionnel",
    'past-first': "Passé",
    'past-second': "Passé deuxième forme",
    'imperative': "Impératif",
    'infinitive': "Infinitif",
    'gerund': "Gérondif",
    'participle': "Participe",
}
SHORT_LIST = {
    'indicative': ["simple-past", "antérieur-past"],
    'subjunctive': ["imperfect", "pluperfect"],
    'conditional': ["past-second"],
    'imperative': ["past"],
    'gerund': [],
    'infinitive': [],
    'participle': [],
}
AUDIO_LIST = [
    "être",
    "avoir",
    "faire",
    "dire",
    "pouvoir",
    "aller",
    "voir",
    "vouloir",
    "venir",
    "devoir",
    "prendre",
    "trouver",
    "donner",
    "falloir",
    "parler",
    "mettre",
    "savoir",
    "passer",
    "regarder",
    "aimer",
    "croire",
    "demander",
    "rester",
    "répondre",
    "entendre",
    "penser",
    "arriver",
    "connaître",
    "devenir",
    "sentir",
    "sembler",
    "tenir",
    "comprendre",
    "rendre",
    "attendre",
    "sortir",
    "vivre",
    "reprendre",
    "entrer",
    "porter",
    "chercher",
    "revenir",
    "appeler",
    "mourir",
    "partir",
    "jeter",
    "suivre",
    "écrire",
    "montrer",
    "tomber",
    "ouvrir",
    "arrêter",
    "perdre",
    "commencer",
    "paraître",
    "marcher",
    "lever",
    "permettre",
    "asseoir",
    "écouter",
    "monter",
    "apercevoir",
    "recevoir",
    "servir",
    "finir",
    "rire",
    "crier",
    "jouer",
    "tourner",
    "garder",
    "reconnaître",
    "quitter",
    "manger",
    "courir",
    "continuer",
    "oublier",
    "descendre",
    "cacher",
    "poser",
    "tirer",
    "présenter",
    "ajouter",
    "agir",
    "retrouver",
    "offrir",
    "apprendre",
    "tuer",
    "retourner",
    "rencontrer",
    "envoyer",
    "dormir",
    "pousser",
    "rappeler",
    "lire",
    "changer",
    "compter",
    "occuper",
    "frapper",
    "travailler",
    "expliquer",
    "obtenir",
    "rentrer",
    "pleurer",
    "essayer",
    "répéter",
    "payer",
    "apporter",
    "boire",
    "sourire",
    "coucher",
    "causer",
    "exister",
    "raconter",
    "serrer",
    "songer",
    "manquer",
    "nommer",
    "conduire",
    "saisir",
    "demeurer",
    "remettre",
    "disparaître",
    "battre",
    "toucher",
    "apparaître",
    "souffrir",
    "fermer",
    "accepter",
    "tendre",
    "naître",
    "sauver",
    "avancer",
    "traverser",
    "souvenir",
    "couvrir",
    "gagner",
    "former",
    "plaire",
    "embrasser",
    "oser",
    "refuser",
    "décider",
    "produire",
    "charger",
    "mêler",
    "cesser",
    "ressembler",
    "chanter",
    "empêcher",
    "approcher",
    "prier",
    "espérer",
    "échapper",
    "glisser",
    "briller",
    "brûler",
    "placer",
    "juger",
    "suffire",
    "atteindre",
    "annoncer",
    "élever",
    "acheter",
    "mener",
    "préparer",
    "assurer",
    "deviner",
    "considérer",
    "appartenir",
    "représenter",
    "tromper",
    "vendre",
    "craindre",
    "emporter",
    "rouler",
    "posséder",
    "réveiller",
    "aider",
    "découvrir",
    "choisir",
    "prononcer",
    "taire",
    "rêver",
    "appuyer",
    "étendre",
    "trembler",
    "défendre",
    "créer",
    "maintenir",
    "indiquer",
    "promettre",
    "relever",
    "abandonner",
    "ignorer",
    "exprimer",
    "accompagner",
    "adresser",
    "observer",
    "séparer",
    "marier",
    "prévoir",
    "amener",
    "obliger",
    "éclairer",
    "poursuivre",
    "livrer",
    "contenir",
    "fuir",
    "couler",
    "proposer",
    "éprouver",
    "retenir",
    "attacher",
    "voler",
    "surprendre",
    "briser",
    "imaginer",
    "diriger",
    "parvenir",
    "pénétrer",
    "remarquer",
    "éviter",
    "établir",
    "réussir",
    "pencher",
    "habiter",
    "entourer",
    "déclarer",
    "étonner",
    "dresser",
    "durer",
    "fixer",
    "désirer",
    "arracher",
    "entraîner",
    "soutenir",
    "couper",
    "douter",
    "retirer",
    "promener",
    "forcer",
    "examiner",
    "revoir",
    "remplir",
    "terminer",
    "tenter",
    "remonter",
    "installer",
    "soulever",
    "allumer",
    "imposer",
    "respirer",
    "baisser",
    "souffler",
    "attirer",
    "prêter",
    "amuser",
    "éclater",
    "réunir",
    "traiter",
    "traîner",
    "employer",
    "marquer",
    "prouver",
    "importer",
    "exiger",
    "reposer",
    "danser",
    "saluer",
    "accorder",
    "achever",
    "avouer",
    "distinguer",
    "emmener",
    "agiter",
    "hésiter",
    "sonner",
    "composer",
    "enlever",
    "rejoindre",
    "ramener",
    "étudier",
    "partager",
    "chasser",
    "interrompre",
    "éloigner",
    "réduire",
    "engager",
    "éteindre",
    "recommencer",
    "sauter",
    "plaindre",
    "préférer",
    "révéler",
    "subir",
    "rapporter",
    "coûter",
    "réfléchir",
    "remercier",
    "déposer",
    "fumer",
    "affirmer",
    "convenir",
    "vêtir",
    "accomplir",
    "résoudre",
    "plonger",
    "détruire",
    "intéresser",
    "disposer",
    "lisser",
    "verser",
    "obéir",
    "lutter",
    "prétendre",
    "construire",
    "soumettre",
    "peser",
    "troubler",
    "répandre",
    "résister",
    "protéger",
    "enfermer",
    "creuser",
    "grandir",
    "enfoncer",
    "envelopper",
    "prévenir",
    "inspirer",
    "ramasser",
    "endormir",
    "inventer",
    "presser",
    "confier",
    "effacer",
    "reculer",
    "user",
    "nourrir",
    "remplacer",
    "souhaiter",
    "signer",
    "interroger",
    "dominer",
    "commander",
    "supposer",
    "dépasser",
    "accuser",
    "habiller",
    "condamner",
    "menacer",
    "écraser",
    "céder",
    "écarter",
    "réclamer",
    "dessiner",
    "conclure",
    "lier",
    "admettre",
    "attaquer",
    "respecter",
    "pendre",
    "supporter",
    "figurer",
    "profiter",
    "accrocher",
    "calmer",
    "satisfaire",
    "valoir",
    "signifier",
    "inquiéter",
    "assister",
    "inviter",
    "déchirer",
    "risquer",
    "parcourir",
    "rejeter",
    "renoncer",
    "veiller",
    "transformer",
    "tracer",
    "contenter",
    "mériter",
    "précipiter",
    "rompre",
    "caresser",
    "étouffer",
    "animer",
    "casser",
    "fonder",
    "franchir",
    "abattre",
    "discuter",
    "fatiguer",
    "consentir",
    "regretter",
    "joindre",
    "vaincre",
    "consulter",
    "haïr",
    "repousser",
    "exécuter",
    "exposer",
    "voyager",
    "renverser",
    "rassurer",
    "retomber",
    "décrire",
    "mentir",
    "armer",
    "étaler",
    "essuyer",
    "précéder",
    "désigner",
    "détacher",
    "recueillir",
    "croiser",
    "entretenir",
    "surveiller",
    "réserver",
    "confondre",
    "dégager",
    "parer",
    "visiter",
    "détourner",
    "plier",
    "accueillir",
    "redevenir",
    "approuver",
    "emparer",
    "aborder",
    "heurter",
    "noyer",
    "semer",
    "guider",
    "piquer",
    ]
