# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'На жизнь'), (2, 'На рекламу')], default=1),
        ),
    ]
