# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 14:03
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField()),
                ('message', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aor_message', to='postman.Message')),
            ],
        ),
    ]
