# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_auto_20170831_1750'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybb.Topic'),
        ),
    ]
