# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_auto_20170831_1710'),
        ('home', '0002_auto_20170825_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybb.Topic'),
        ),
    ]
