# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lessonpage_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexReviewsReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('review_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_subtitle', models.CharField(blank=True, max_length=1024, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_reviews', to='home.IndexPage')),
                ('referenced_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
