# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indexreviewsreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
    ]
