# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lessonpage_audio_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='is_nav_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagewithsidebar',
            name='is_nav_root',
            field=models.BooleanField(default=False),
        ),
    ]
