# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171102_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexreviewsreferences',
            name='referenced_review_url',
            field=models.URLField(null=True),
        ),
    ]
