# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_indexreviewsreferences_referenced_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexreviewsreferences',
            name='referenced_review_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
