# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_lessontopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontopic',
            old_name='lesson_number',
            new_name='lesson_page',
        ),
    ]
