# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0007_auto_20170703_1731'),
        ('home', '0010_auto_20170712_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontopic',
            name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='lessontopic',
            name='topic_ptr',
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pybb.Topic'),
        ),
        migrations.DeleteModel(
            name='LessonTopic',
        ),
    ]
