# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171102_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexReviewsReferences',
            new_name='IndexReviews',
        ),
    ]
