# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170713_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='have_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='pybb.Topic'),
        ),
    ]
