# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171102_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexreviews',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
