# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170713_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonpage',
            old_name='have_topic',
            new_name='has_own_topic',
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybb.Topic'),
        ),
    ]
