# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170714_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybb.Topic'),
        ),
    ]
