# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_indexreviews_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexreviews',
            name='name',
        ),
    ]
