# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170717_1524'),
        ('home', '0006_auto_20170818_2239'),
    ]

    operations = [
    ]
