# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170819_0906'),
        ('home', '0015_merge_20170820_1342'),
    ]

    operations = [
    ]
