# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170717_1524')
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpage',
            name='reference_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='reference_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagewithsidebar',
            name='reference_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
