# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagewithsidebar',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
    ]
