# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171204_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
