# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_articlepage_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_nav_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
    ]
