# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20171205_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='show_in_sitemap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultpage',
            name='show_in_sitemap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='show_in_sitemap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagewithsidebar',
            name='show_in_sitemap',
            field=models.BooleanField(default=True),
        ),
    ]
