# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20171220_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertCode',
            new_name='AdvertismentSnippet',
        ),
    ]
