# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20171220_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertismentSnippet',
            new_name='AdvertisementSnippet',
        ),
    ]
