# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20171221_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementSnippet',
            new_name='InlineAdvertisementSnippet',
        ),
    ]
