# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 10:59
from __future__ import unicode_literals

from django.db import migrations
import home.blocks.TabsBlock
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20171221_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))))),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('post', wagtail.wagtailcore.blocks.StructBlock((('post_id', wagtail.wagtailcore.blocks.IntegerBlock()),))))),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='comments_for_lesson',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('post', wagtail.wagtailcore.blocks.StructBlock((('post_id', wagtail.wagtailcore.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='dictionary',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('translations', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('word', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('translation', wagtail.wagtailcore.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.wagtailcore.blocks.StructBlock((('post_id', wagtail.wagtailcore.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('tabs', home.blocks.TabsBlock.TabsBlock()), ('translations', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('word', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('translation', wagtail.wagtailcore.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.wagtailcore.blocks.StructBlock((('post_id', wagtail.wagtailcore.blocks.IntegerBlock()),))), ('choosen_reviews', wagtail.wagtailcore.blocks.StructBlock(())))),
        ),
    ]
