# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20171221_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarAdvertisementSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
