# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20171221_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarAdvertisementSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body', wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock())))),
            ],
        ),
    ]
