# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 11:53
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_sidebaradvertisementsnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebaradvertisementsnippet',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.AdvertisementSnippet)),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock())), blank=True),
        ),
    ]
