# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_sidebaradvertisementsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaradvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_page', 'Lesson Page'), ('page_with_sidebar', 'Page with Sidebar'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
