# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_sidebaradvertisementsnippet_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaradvertisementsnippet',
            name='head',
            field=wagtail.core.fields.StreamField((('html', wagtail.core.blocks.RawHTMLBlock()),), blank=True),
        ),
    ]
