# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_sidebaradvertisementsnippet_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebaradvertisementsnippet',
            name='page_type',
        ),
        migrations.AddField(
            model_name='sidebaradvertisementsnippet',
            name='placements',
            field=models.CharField(choices=[('lesson_page', 'Lesson Page Sidebar'), ('lesson_page_bottom', 'Lesson Page Bottom'), ('page_with_sidebar', '"Page with sidebar" Sidebar'), ('page_with_sidebar_bottom', '"Page with Sidebar" Bottom'), ('article_page', 'Article Page Sidebar'), ('article_page_bottom', 'Article Page Bottom'), ('index_page', 'Title Page Sidebar'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
