# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20171221_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SidebarAdvertisementSnippet',
            new_name='PlacementAdvertisementSnippet',
        ),
    ]
