# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20171222_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementadvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page Sidebar'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
