# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20171222_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacementAdvertisementSnippet',
            new_name='PageLayoutAdvertisementSnippet',
        ),
    ]
