# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 09:28
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20171222_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementSnippet',
            new_name='InlineAdvertisementSnippet',
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='comments_for_lesson',
            field=wagtail.wagtailcore.fields.StreamField((('advertisement', wagtail.wagtailcore.blocks.StructBlock((('advertisement', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('document', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()),))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('audio', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.CharBlock()), ('downloadable', wagtail.wagtailcore.blocks.BooleanBlock(required=False))))), ('video', wagtail.wagtailcore.blocks.StructBlock((('source', wagtail.wagtailcore.blocks.CharBlock()), ('poster', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('post', wagtail.wagtailcore.blocks.StructBlock((('post_id', wagtail.wagtailcore.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
    ]
