# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 09:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20171222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayoutadvertisementsnippet',
            name='body',
            field=wagtail.core.fields.StreamField((('html', wagtail.core.blocks.RawHTMLBlock()),), blank=True),
        ),
    ]
