# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20171222_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayoutadvertisementsnippet',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('top', 'Top'), ('bottom', 'Bottom'), ('none', 'None'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom')], default='none', max_length=100),
        ),
    ]
