# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20171222_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('body_bottom', 'Body Bottom'), ('none', 'None'), ('comments_for_lesson_bottom', 'Comments for Lesson Bottom'), ('dictionary_bottom', 'Dictionary Bottom'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom')], default='none', max_length=100),
        ),
    ]
