# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import home.blocks.TabsBlock
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20171222_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlineadvertisementsnippet',
            name='body_mobile',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()),))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))))),
        ),
        migrations.AlterField(
            model_name='inlineadvertisementsnippet',
            name='body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='inlineadvertisementsnippet',
            name='header',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()),))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),))))),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='comments_for_lesson',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()),))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='dictionary',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()),))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('translations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('word', wagtail.core.blocks.RichTextBlock(required=True)), ('translation', wagtail.core.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock())), blank=True),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('body_bottom', 'Body Bottom'), ('none', 'None'), ('comments_for_lesson_bottom', 'Comments for Lesson Bottom'), ('dictionary_bottom', 'Dictionary Bottom'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom'), ('index_page_sidebar_top', 'Title Page Sidebar Top'), ('index_page_sidebar_middle', 'Title Page Sidebar Middle'), ('index_page_sidebar_bottom', 'Title Page Sidebar Bottom')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()),))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('tabs', home.blocks.TabsBlock.TabsBlock()), ('translations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('word', wagtail.core.blocks.RichTextBlock(required=True)), ('translation', wagtail.core.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),))), ('choosen_reviews', wagtail.core.blocks.StructBlock(())))),
        ),
    ]
