# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20180202_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewithsidebar',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
