# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_indexpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('none', 'None'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom')], default='none', max_length=100),
        ),
    ]
