# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20180208_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexreviews',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='indexreviews',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='indexreviews',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
