# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import home.blocks.TabsBlock
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20180208_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))))),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('none', 'None')], default='article_page', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('none', 'None')], default='index_page', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),))))),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='comments_for_lesson',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='dictionary',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('translations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('word', wagtail.core.blocks.RichTextBlock(required=True)), ('translation', wagtail.core.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='other_tabs',
            field=wagtail.core.fields.StreamField((('tab', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('href', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.StreamBlock((('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('topic', wagtail.core.blocks.StructBlock((('topic_id', wagtail.core.blocks.IntegerBlock()),))), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),))))))))),)),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='body',
            field=wagtail.core.fields.StreamField((('advertisement', wagtail.core.blocks.StructBlock((('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))))), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock((('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))))), ('video', wagtail.core.blocks.StructBlock((('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))))), ('tabs', home.blocks.TabsBlock.TabsBlock()), ('translations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('word', wagtail.core.blocks.RichTextBlock(required=True)), ('translation', wagtail.core.blocks.RichTextBlock(required=True)))), template='blocks/transcriptions.html')), ('post', wagtail.core.blocks.StructBlock((('post_id', wagtail.core.blocks.IntegerBlock()),))), ('choosen_reviews', wagtail.core.blocks.StructBlock(())))),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
