# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 11:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20180529_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonpage',
            options={'permissions': (('listen_lesson', 'Listen lesson'),)},
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='other_tabs',
            field=wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('href', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('topic', wagtail.core.blocks.StructBlock([('topic_id', wagtail.core.blocks.IntegerBlock())])), ('post', wagtail.core.blocks.StructBlock([('post_id', wagtail.core.blocks.IntegerBlock())]))]))]))], blank=True),
        ),
    ]
