# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='datetime',
            new_name='datetime_update',
        ),
    ]
