# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20180831_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 19, 40, 22, 712795)),
        ),
    ]
