# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_payment_datetime_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
