# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20180831_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='e_product_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='e_product_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='e_product_sku',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='e_transaction_total',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
