# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20180927_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='e_product_name',
        ),
    ]
