# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_remove_payment_e_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='need_payment',
            field=models.BooleanField(default=False),
        ),
    ]
