# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0008_auto_20181024_1725'),
        ('home', '0066_lessonpage_need_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.URLField()),
                ('fail', models.URLField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinkoff_merchant.Payment')),
            ],
        ),
    ]
