# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_articlepage_without_sightbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewithsidebar',
            name='without_right_sightbar',
            field=models.BooleanField(default=False),
        ),
    ]
