# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_pagewithsidebar_without_right_sightbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='remains',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='home.LessonPage'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
