# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20181224_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
