# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20181225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlineadvertisementsnippet',
            name='adunit_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inlineadvertisementsnippet',
            name='adunit_sizes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
