# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20190327_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adunit_code', models.CharField(max_length=100, unique=True)),
                ('adunit_sizes', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
