# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks.field_block


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_adunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('script', models.TextField(verbose_name=wagtail.core.blocks.field_block.RawHTMLBlock)),
            ],
        ),
    ]
