# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='size_mapping',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Mapping'),
        ),
    ]
