# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_adunit_size_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='script',
            field=models.TextField(max_length=1000),
        ),
    ]
