# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20190404_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='exercise',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='placement',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('none', 'None'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom'), ('in_house_sidebar', 'In-House Sidebar')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='repetition_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Révision'),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('none', 'None'), ('resume_top', 'Resume Top'), ('resume_bottom', 'Resume Bottom'), ('revision_top', 'Revision Top'), ('revision_bottom', 'Revision Bottom'), ('in_house_sidebar', 'In-House Sidebar')], default='none', max_length=100),
        ),
    ]
