# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 12:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20190514_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='exercise',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Домашка'),
        ),
    ]
