# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 11:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20190710_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='resume_populaire',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))]))], null=True, verbose_name='Народный конспект'),
        ),
    ]
