# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 16:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20190827_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='additional_exercise',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Дополнительная Домашка'),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='other_tabs',
            field=wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('invisible_for_all', wagtail.core.blocks.BooleanBlock(help_text='Табик виден только для администраторов, приоритет над всеми', required=False)), ('visible_only_if_payed', wagtail.core.blocks.BooleanBlock(help_text='Табик виден только для пользователей, которые активировали урок', required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('href', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('topic', wagtail.core.blocks.StructBlock([('topic_id', wagtail.core.blocks.IntegerBlock())])), ('post', wagtail.core.blocks.StructBlock([('post_id', wagtail.core.blocks.IntegerBlock())]))]))]))], blank=True),
        ),
    ]
