# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 17:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_auto_20190924_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='additional_exercise',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Exercises De Lecon'),
        ),
    ]
