# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_auto_20191025_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='exercise',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('learning_apps', wagtail.core.blocks.StructBlock([('app_id', wagtail.core.blocks.CharBlock(required=True)), ('number', wagtail.core.blocks.IntegerBlock(required=True)), ('show_lesson_number', wagtail.core.blocks.BooleanBlock(default=True)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('height', wagtail.core.blocks.CharBlock(default='500px')), ('width', wagtail.core.blocks.CharBlock(default='100%'))]))], blank=True, null=True, verbose_name='Домашка'),
        ),
    ]
