# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.blocks.AlsoReadBlock
import home.blocks.TabsBlock
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0086_auto_20191028_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='reference_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('advertisement', wagtail.core.blocks.StructBlock([('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('read_also', home.blocks.AlsoReadBlock.AlsoReadBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='body',
            field=wagtail.core.fields.StreamField([('advertisement', wagtail.core.blocks.StructBlock([('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('tabs', home.blocks.TabsBlock.TabsBlock()), ('translations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('word', wagtail.core.blocks.RichTextBlock(required=True)), ('translation', wagtail.core.blocks.RichTextBlock(required=True))]), template='blocks/transcriptions.html')), ('post', wagtail.core.blocks.StructBlock([('post_id', wagtail.core.blocks.IntegerBlock())])), ('choosen_reviews', wagtail.core.blocks.StructBlock([])), ('read_also', home.blocks.AlsoReadBlock.AlsoReadBlock())], blank=True),
        ),
    ]
