# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 11:13
from __future__ import unicode_literals

import annoying.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0088_auto_20200423_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailPageNavTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('page', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nav_tree', to='wagtailcore.Page')),
            ],
        ),
    ]
