# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_indexreviews_show_in_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='transcript_srt',
            field=models.FileField(default=None, null=True, upload_to='home/transcripts'),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='transcript_text',
            field=models.TextField(default=None, null=True),
        ),
    ]
