# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_auto_20201008_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='transcript_srt',
            field=models.FileField(blank=True, default=None, null=True, upload_to='home/transcripts'),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='transcript_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
