# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 13:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_lessonpage_transcript_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='has_transcript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='transcript',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
