# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20201120_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='transcript_html',
            field=models.TextField(default=''),
        ),
    ]
