# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import home.blocks.AlsoReadBlock
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0096_lessonpage_transcript_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('advertisement', wagtail.core.blocks.StructBlock([('advertisement', wagtail.snippets.blocks.SnippetChooserBlock(home.models.InlineAdvertisementSnippet)), ('disable', wagtail.core.blocks.BooleanBlock(required=False))])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('read_also', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Читайте также', required=True)), ('images_size', wagtail.core.blocks.IntegerBlock(default=64, required=True)), ('links', home.blocks.AlsoReadBlock.ArticleLinks())])), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))])), ('collapse', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.TextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))])), ('nested_collapse', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.TextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))]))], required=True))]))], required=True))])), ('bootstrap_callout', wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('bs-callout-primary', 'Primary'), ('bs-callout-secondary', 'Secondary'), ('bs-callout-warning', 'Warning'), ('bs-callout-danger', 'Danger'), ('bs-callout-success', 'Success'), ('bs-callout-info', 'Info')])), ('heading', wagtail.core.blocks.TextBlock(required=False)), ('heading_color', wagtail.core.blocks.BooleanBlock(default=True)), ('text', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())]))]))], blank=True)),
                ('menu_title', models.TextField(blank=True)),
                ('reference_title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('reference_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='other_tabs',
            field=wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('invisible_for_all', wagtail.core.blocks.BooleanBlock(help_text='Табик виден только для администраторов, приоритет над всеми', required=False)), ('visible_only_if_payed', wagtail.core.blocks.BooleanBlock(help_text='Табик виден только для пользователей, которые активировали урок', required=False)), ('visible_only_if_authorised', wagtail.core.blocks.BooleanBlock(help_text='Табик виден тольо для залогиненых пользователей', required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('href', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.IntegerBlock(required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('audio', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock()), ('downloadable', wagtail.core.blocks.BooleanBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.CharBlock()), ('poster', wagtail.core.blocks.CharBlock(required=False))])), ('topic', wagtail.core.blocks.StructBlock([('topic_id', wagtail.core.blocks.IntegerBlock())])), ('post', wagtail.core.blocks.StructBlock([('post_id', wagtail.core.blocks.IntegerBlock())])), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))])), ('collapse', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.TextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))])), ('nested_collapse', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.TextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('floating_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_caption', wagtail.core.blocks.CharBlock(help_text='Подпись под картинкой', required=False)), ('width_large', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('width_small', wagtail.core.blocks.IntegerBlock(default=200, required=True)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('rightimg', 'Float Right'), ('leftimg', 'Float Left')])), ('content', wagtail.core.blocks.StreamBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], required=True))]))], required=True))]))], required=True))]))]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='transcript',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='transcript_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
