# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20210519_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastpage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='podcast_page', max_length=100),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='page_type',
            field=models.CharField(blank=True, choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='article_page', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='index_page', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagelayoutadvertisementsnippet',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagewithsidebar',
            name='page_type',
            field=models.CharField(choices=[('lesson_a1', 'Lesson A1'), ('lesson_a2', 'Lesson A2'), ('lesson_b2', 'Lesson_B2'), ('lesson_page', 'Lesson Page'), ('page_with_sidebar', '"Page with sidebar"'), ('article_page', 'Article Page'), ('index_page', 'Title Page'), ('conjugation_index', 'Conjugation Title'), ('conjugation_verb', 'Conjugation Verb'), ('podcast_page', 'Podcast Page'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
