# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-06 15:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_pagelayoutadvertisementsnippet_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='sizes',
            field=wagtail.core.fields.StreamField([('size', wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('vgt', 'viewport size greater than'), ('vlt', 'viewport size less than'), ('cgt', 'parent container size greater than or equal'), ('clt', 'parent container size less than or equal')], required=False)), ('window_or_container_size', wagtail.core.blocks.CharBlock(help_text='320px', required=False)), ('ad_unit_size', wagtail.core.blocks.CharBlock(help_text='250px, 100%, ...', required=True))]))], blank=True),
        ),
    ]
