# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexSpeechKitTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=5000, null=True)),
                ('ssml', models.CharField(default=None, max_length=5000, null=True)),
                ('lang', models.CharField(choices=[('ru-RU', 'Russian')], default=None, max_length=10, null=True)),
                ('voice', models.CharField(choices=[('alena', 'alena'), ('filipp', 'filipp')], default=None, max_length=10, null=True)),
                ('emotion', models.CharField(choices=[('neutral', 'neutral'), ('whisper', 'whisper'), ('friendly', 'friendly'), ('good', 'good'), ('strict', 'strict'), ('evil', 'evil')], default=None, max_length=10, null=True)),
                ('format', models.CharField(choices=[('lpcm', 'lpcm'), ('oggopus', 'oggopus'), ('mp3', 'mp3')], default=None, max_length=10, null=True)),
                ('sample_rate', models.CharField(choices=[('8000', '8000'), ('16000', '16000'), ('48000', '48000')], default=None, max_length=10, null=True)),
                ('task_status', models.CharField(default='CREATED', max_length=10, null=True)),
                ('error', models.BooleanField(default=False)),
                ('stream', models.BinaryField(default=None, null=True)),
            ],
        ),
    ]
