# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='format',
            field=models.CharField(choices=[('lpcm', 'lpcm'), ('oggopus', 'oggopus'), ('mp3', 'mp3')], default='mp3', max_length=10),
        ),
    ]
