# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0002_auto_20250129_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexspeechkittask',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
