# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0003_yandexspeechkittask_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='sample_rate',
            field=models.CharField(blank=True, choices=[('8000', '8000'), ('16000', '16000'), ('48000', '48000')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='ssml',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='stream',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
