# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0004_auto_20250130_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexspeechkittask',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
