# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-31 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0005_yandexspeechkittask_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='format',
            field=models.CharField(choices=[('lpcm', 'lpcm'), ('oggopus', 'oggopus'), ('mp3', 'mp3')], default='lpcm', max_length=10),
        ),
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='sample_rate',
            field=models.CharField(blank=True, choices=[('8000', '8000'), ('16000', '16000'), ('48000', '48000')], default='48000', max_length=10, null=True),
        ),
    ]
