# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0006_auto_20250131_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexspeechkittask',
            name='voice',
            field=models.CharField(choices=[('alena', 'alena'), ('jane', 'jane'), ('omazh', 'omazh'), ('filipp', 'filipp'), ('ermil', 'ermil')], default=None, max_length=10, null=True),
        ),
    ]
