# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_errors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlog',
            name='value',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
