BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXX BBBBBBBB
BBBBB BBBBBBB
  XXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBB

  BBBB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
    BB BBBBBBBBBB
      XXXX
        BBB BBBBBBBB BB BBBBBBBBBB
          XXXXXXXXX
        BBBBBB
      XXXXX
    BBBBB
  BBBBBBB

  FFFFFFFF
  XXXXX XXXXXXBBBBBBB BBBBBBBBXXXXXX XX XXXXXX XXXXXXXXXXXXX
BBBBBBBB
