BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBB
    XXXXXXX
    XXXXX XXXXXXXXBBBBBBB BBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB
