# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(editable=False, verbose_name='Сумма в копейках')),
                ('order_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Номер заказа')),
                ('description', models.TextField(blank=True, default='', editable=False, max_length=250, verbose_name='Описание')),
                ('success', models.BooleanField(default=False, editable=False, verbose_name='Успешно проведен')),
                ('status', models.CharField(default='', editable=False, max_length=20, verbose_name='Статус транзакции')),
                ('payment_id', models.CharField(default='', editable=False, max_length=20, verbose_name='Уникальный идентификатор транзакции в системе банка')),
                ('error_code', models.CharField(default='', editable=False, max_length=20, verbose_name='Код ошибки')),
                ('payment_url', models.CharField(blank=True, default='', editable=False, help_text='Ссылка на страницу оплаты. По умолчанию ссылка доступна в течении 24 часов.', max_length=100, verbose_name='Ссылка на страницу оплаты.')),
                ('message', models.TextField(blank=True, default='', editable=False, verbose_name='Краткое описание ошибки')),
                ('details', models.TextField(blank=True, default='', editable=False, verbose_name='Подробное описание ошибки')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='Электронный адрес для отправки чека покупателю')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон покупателя')),
                ('taxation', models.CharField(choices=[('osn', 'общая СН'), ('usn_income', 'упрощенная СН (доходы)'), ('usn_income_outcome', 'упрощенная СН (доходы минус расходы)'), ('envd', 'единый налог на вмененный доход'), ('esn', 'единый сельскохозяйственный налог'), ('patent', 'патентная СН')], max_length=20, verbose_name='Система налогообложения')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tinkoff_merchant.Payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Данные чека',
                'verbose_name_plural': 'Данные чеков',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование товара')),
                ('price', models.IntegerField(verbose_name='Цена в копейках')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Количество/вес')),
                ('amount', models.IntegerField(verbose_name='Сумма в копейках')),
                ('tax', models.CharField(choices=[('none', 'без НДС'), ('vat0', 'НДС по ставке 0%'), ('vat10', 'НДС чека по ставке 10%'), ('vat18', 'НДС чека по ставке 18%'), ('vat110', 'НДС чека по расчетной ставке 10/110'), ('vat118', 'НДС чека по расчетной ставке 18/118')], max_length=10, verbose_name='Ставка налога')),
                ('ean13', models.CharField(blank=True, default='', max_length=20, verbose_name='Штрих-код')),
                ('shop_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Код магазина')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinkoff_merchant.Receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name': 'Информация о товаре',
                'verbose_name_plural': 'Информация о товарах',
            },
        ),
    ]
