# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0002_remove_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='', editable=False, max_length=100, unique=True, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
