# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0003_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
