# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0007_auto_20181024_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_key',
            field=models.CharField(default=None, editable=False, max_length=36, null=True, verbose_name='Идентификатор покупателя'),
        ),
    ]
