# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0008_auto_20181024_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(choices=[('coffee_cup', 'Чашки кофе'), ('ticket', 'Билеты')], default='', max_length=20, verbose_name='Категория товара'),
        ),
    ]
