# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0009_auto_20181025_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
