# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0011_auto_20181026_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tinkoff_merchant.Payment', verbose_name='Заказ'),
        ),
    ]
