# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0012_auto_20181026_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.CharField(blank=True, default='', editable=False, help_text='Ссылка на страницу оплаты. По умолчанию ссылка доступна в течение 24 часов.', max_length=100, verbose_name='Ссылка на страницу оплаты.'),
        ),
    ]
