# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0013_auto_20181113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(choices=[('coffee_cups', 'Чашки кофе'), ('tickets', 'Тикеты')], default='', max_length=20, verbose_name='Категория товара'),
        ),
    ]
