# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0014_auto_20191028_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rebill_id',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Идентификатор автоплатежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recurrent',
            field=models.BooleanField(default=False, verbose_name='Идентификатор родительского платежа'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(choices=[('coffee_cups', 'Чашки кофе'), ('tickets', 'Тикеты'), ('donations', 'Пожертвования')], default='', max_length=20, verbose_name='Категория товара'),
        ),
    ]
