# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0017_auto_20210929_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='tinkoff_merchant.Payment'),
        ),
    ]
