# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-11 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinkoff_merchant', '0018_auto_20210929_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinkoff_payments', related_query_name='tinkoff_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
