# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-05 14:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0020_payment_response_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='request_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
