# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_merchant', '0023_auto_20230301_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectToPaymentUrl',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_to_payment_url', to='tinkoff_merchant.Payment')),
            ],
        ),
    ]
