# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='subjunctiv',
            new_name='subjunctive',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='aspirated_h',
            new_name='aspirate_h',
        ),
    ]
