# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0004_auto_20180316_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='intransitive',
            field=models.BooleanField(default=False),
        ),
    ]
