# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0005_verb_intransitive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='intransitive',
            new_name='maison',
        ),
    ]
