# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0006_auto_20180321_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='no_red_end',
            field=models.BooleanField(default=False),
        ),
    ]
