# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0007_template_no_red_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='infinitive_no_accents',
            field=models.CharField(default='', max_length=100),
        ),
    ]
