# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0008_verb_infinitive_no_accents'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='only_reflexive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='reflexive',
            field=models.CharField(default='', max_length=100),
        ),
    ]
