# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 09:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0009_auto_20180326_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='new_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
