# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0010_template_new_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='second_form',
            field=models.BooleanField(default=False),
        ),
    ]
