# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0011_template_second_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='has_passive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='has_reflexive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='has_s_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='has_second_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='no_female',
            field=models.BooleanField(default=False),
        ),
    ]
