# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0012_auto_20180412_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='only_reflexive',
            new_name='reflexive_only',
        ),
    ]
