# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0014_auto_20180412_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='forms_count',
            field=models.IntegerField(default=1),
        ),
    ]
