# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0015_template_forms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='reflexive_no_accents',
            field=models.CharField(default='', max_length=100),
        ),
    ]
