# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0017_reflexiveverb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='has_reflexive',
        ),
    ]
