# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0020_delete_reflexiveverb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflexiveVerb',
            fields=[
                ('verb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conjugation.Verb')),
                ('infinitive', models.CharField(max_length=100)),
                ('infinitive_no_accents', models.CharField(max_length=100)),
                ('deffective', models.BooleanField(default=False)),
                ('impersonal', models.BooleanField(default=False)),
            ],
        ),
    ]
