# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0022_remove_verb_reflexive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeffectivePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicative_compose_past', models.BooleanField(default=False)),
                ('indicative_anterieur_past', models.BooleanField(default=False)),
                ('indicative_pluperfect', models.BooleanField(default=False)),
                ('indicative_anterieur_future', models.BooleanField(default=False)),
                ('subjunctive_past', models.BooleanField(default=False)),
                ('subjunctive_pluperfect', models.BooleanField(default=False)),
                ('conditional_past_first', models.BooleanField(default=False)),
                ('conditional_past_second', models.BooleanField(default=False)),
                ('imperative_past', models.BooleanField(default=False)),
                ('infinitive_past', models.BooleanField(default=False)),
                ('gerund_past', models.BooleanField(default=False)),
            ],
        ),
    ]
