# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0023_deffectivepattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflexiveverb',
            old_name='deffective',
            new_name='is_deffective',
        ),
    ]
