# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0024_auto_20180425_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='is_deffective',
            field=models.BooleanField(default=False),
        ),
    ]
