# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0025_verb_is_deffective'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflexiveverb',
            name='deffective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conjugation.DeffectivePattern'),
        ),
        migrations.AddField(
            model_name='verb',
            name='deffective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conjugation.DeffectivePattern'),
        ),
    ]
