# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0026_auto_20180425_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflexiveverb',
            old_name='impersonal',
            new_name='is_impersonal',
        ),
    ]
