# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0030_auto_20180427_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='regle_id',
            new_name='id_regle',
        ),
    ]
