# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0032_verb_regle'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='audio_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
