# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0033_verb_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regle',
            name='text_fr',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='regle',
            name='text_rus',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
