# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0034_auto_20180510_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
