# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0035_verb_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='group_str',
            field=models.CharField(default='', max_length=256),
        ),
    ]
