# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0037_remove_verb_is_deffective'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='pp_invariable',
            field=models.BooleanField(default=False),
        ),
    ]
