# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0039_pollyaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollyaudio',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
