# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0041_auto_20190215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='text',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
