# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0042_pollyaudio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('verb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conjugation.Verb')),
            ],
        ),
        migrations.AddField(
            model_name='pollyaudio',
            name='text_type',
            field=models.CharField(choices=[('ssml', 'ssml'), ('text', 'text')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='text',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='url',
            field=models.URLField(default=None, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
