# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0043_auto_20190218_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='datetime_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
            preserve_default=False,
        ),
    ]
