# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0045_auto_20190218_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='task_id',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pollyaudio',
            name='task_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('inProgress', 'inProgress'), ('completed', 'completed'), ('failed', 'failed')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='language_code',
            field=models.CharField(choices=[('fr-FR', 'French'), ('ru-RU', 'Russian')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='output_format',
            field=models.CharField(choices=[('json', 'json'), ('mp3', 'mp3'), ('ogg_vorbis', 'ogg_vorbis'), ('pcm', 'pcm')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='sample_rate',
            field=models.CharField(choices=[('8000', '8000'), ('16000', '16000'), ('22050', '22050')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='voice_id',
            field=models.CharField(choices=[('Lea', 'lea'), ('Celine', 'celine'), ('Mathieu', 'matthieu'), ('Maxim', 'maxim'), ('Tatyana', 'tatyana')], default=None, max_length=16, null=True),
        ),
    ]
