# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0046_auto_20190218_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='request_characters',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
