# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0047_pollyaudio_request_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollyaudio',
            name='datetime_update',
        ),
        migrations.AlterField(
            model_name='pollyaudio',
            name='datetime_creation',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата создания'),
        ),
    ]
