# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0049_auto_20190225_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrVerbTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.CharField(default=None, max_length=800, null=True)),
                ('type', models.CharField(choices=[('verb_translation', 'Перевод'), ('example', 'Пример использования'), ('collocation', 'Устойчивое выражение'), ('idiom', 'Идиоматическое выражение'), ('phraseme', '')], default=None, max_length=10, null=True)),
                ('status', models.CharField(choices=[('', ''), ('', ''), ('', '')], default=None, max_length=10, null=True)),
                ('order', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=1000)),
                ('children', models.ManyToManyField(to='conjugation.FrVerbTranslation')),
                ('fr_tag', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conjugation.FrTag')),
                ('fr_verb', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conjugation.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='RuTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('word_normalise', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frverbtranslation',
            name='translations_tags',
            field=models.ManyToManyField(to='conjugation.RuTag'),
        ),
    ]
