# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0050_auto_20190307_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrVerbTranslation',
            new_name='Fr2RuTranslation',
        ),
    ]
