# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0051_auto_20190307_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fr2rutranslation',
            old_name='translations',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='fr2rutranslation',
            old_name='translations_tags',
            new_name='translation_tags',
        ),
        migrations.AddField(
            model_name='fr2rutranslation',
            name='fr_word',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fr2rutranslation',
            name='fr_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugation.FrTag'),
        ),
        migrations.AlterField(
            model_name='fr2rutranslation',
            name='fr_verb',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugation.Verb'),
        ),
    ]
