# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0053_auto_20190307_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='conjugation.Fr2RuTranslation')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='conjugation.Fr2RuTranslation')),
            ],
        ),
        migrations.AddField(
            model_name='fr2rutranslation',
            name='children',
            field=models.ManyToManyField(through='conjugation.ChildrenRelation', to='conjugation.Fr2RuTranslation'),
        ),
    ]
