# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0054_auto_20190307_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenrelation',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fr2rutranslation',
            name='translation_link',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_reverse', to='conjugation.Fr2RuTranslation'),
        ),
        migrations.AlterField(
            model_name='fr2rutranslation',
            name='type',
            field=models.CharField(choices=[('verb_translation', 'Перевод'), ('example', 'Пример использования'), ('collocation', 'Устойчивое выражение'), ('idiom', 'Идиоматическое выражение'), ('none', 'Не выбрано')], default=None, max_length=10, null=True),
        ),
    ]
