# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0055_auto_20190321_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fr2rutranslation',
            options={'ordering': ['order', 'fr_verb']},
        ),
        migrations.AddField(
            model_name='fr2rutranslation',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Поле для сортировки'),
        ),
    ]
