# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0056_auto_20190411_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
