# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0001_initial'),
        ('conjugation', '0058_verb_homonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyaudio',
            name='polly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask'),
        ),
    ]
