# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0060_auto_20190704_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('verb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conjugation.Verb')),
            ],
        ),
        migrations.RemoveField(
            model_name='childrenrelation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='childrenrelation',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='fr2rutranslation',
            name='children',
        ),
        migrations.RemoveField(
            model_name='fr2rutranslation',
            name='fr_tag',
        ),
        migrations.RemoveField(
            model_name='fr2rutranslation',
            name='fr_verb',
        ),
        migrations.RemoveField(
            model_name='fr2rutranslation',
            name='translation_link',
        ),
        migrations.RemoveField(
            model_name='fr2rutranslation',
            name='translation_tags',
        ),
        migrations.DeleteModel(
            name='ChildrenRelation',
        ),
        migrations.DeleteModel(
            name='Fr2RuTranslation',
        ),
        migrations.DeleteModel(
            name='FrTag',
        ),
        migrations.DeleteModel(
            name='RuTag',
        ),
    ]
