# Generated by Django 2.2.12 on 2020-04-24 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0066_verb_main_part_no_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='new_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
