# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0070_except'),
    ]

    operations = [
        migrations.RenameField(
            model_name='except',
            old_name='indicative_antérieur-future',
            new_name='indicative_antérieur_future',
        ),
        migrations.RenameField(
            model_name='except',
            old_name='indicative_antérieur-past',
            new_name='indicative_antérieur_past',
        ),
        migrations.RenameField(
            model_name='except',
            old_name='indicative_composé-past',
            new_name='indicative_composé_past',
        ),
        migrations.RenameField(
            model_name='except',
            old_name='indicative_simple-past',
            new_name='indicative_simple_past',
        ),
    ]
