# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0070_except'),
    ]

    operations = [
        migrations.AddField(
            model_name='except',
            name='name',
            field=models.CharField(default='Exception', max_length=100),
        ),
    ]
