# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0071_auto_20200826_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='except',
            name='override_blank',
            field=models.BooleanField(default=False, help_text='If true, exception will override blank strings in the formula, this could lead to results like "None<verb>None"', verbose_name='Override blank'),
        ),
    ]
