# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0072_except_override_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='is_etre_verb',
            field=models.BooleanField(default=False),
        ),
    ]
