# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugation', '0074_auto_20221207_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='except',
            name='pronominal_en',
            field=models.BooleanField(default=False, verbose_name='S-EN'),
        ),
        migrations.AlterField(
            model_name='except',
            name='pronominal_en_negation',
            field=models.BooleanField(default=False, verbose_name='S-EN_NEGATIVE'),
        ),
        migrations.AlterField(
            model_name='except',
            name='question_pronominal_en',
            field=models.BooleanField(default=False, verbose_name='QUESTION_S-EN'),
        ),
        migrations.AlterField(
            model_name='except',
            name='question_pronominal_en_negation',
            field=models.BooleanField(default=False, verbose_name='QUESTION_S-EN_NEGATIVE'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='audio_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='deffective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conjugation.DeffectivePattern'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='homonym',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
