# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 16:34
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json
import mass_mailer.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('use_tls', models.BooleanField()),
                ('use_ssl', models.BooleanField()),
                ('messages_per_second', models.IntegerField(default=50)),
                ('messages_per_hour', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_subject', models.CharField(blank=True, max_length=64)),
                ('template_html', models.TextField(blank=True, help_text='You can ')),
                ('template_txt', models.TextField(blank=True)),
                ('extra_headers', annoying.fields.JSONField(blank=True, default=None, deserializer=json.loads, help_text='JSON Format', null=True, serializer=annoying.fields.dumps)),
                ('from_email', models.EmailField(default='no_reply@files.le-francais.ru', max_length=254)),
                ('reply_to', models.EmailField(max_length=254, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('send_datetime', models.DateTimeField(null=True)),
                ('email_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mass_mailer.EmailSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', mass_mailer.models.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'default')]), default=[], size=None)),
                ('subscribed', models.BooleanField(default=True)),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('0', 'Users w/o activations'), ('1', 'Users with payments')], max_length=12), blank=True, default=list, size=None)),
                ('name', models.CharField(max_length=64)),
                ('first_payment_was', models.DateField(null=True)),
                ('last_payment_was', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='recipients_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mass_mailer.UsersFilter'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.ManyToManyField(blank=True, null=True, related_name='mass_mailer_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
