# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='manual_email_list',
            field=models.TextField(default=None, help_text='Comma-separated list of emails, for testing purposes.', max_length=1024, null=True),
        ),
    ]
