# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 13:57
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='extra_headers',
            field=annoying.fields.JSONField(blank=True, default=dict, deserializer=json.loads, help_text='JSON Dict Format', serializer=annoying.fields.dumps),
        ),
    ]
