# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mass_mailer.EmailSettings'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mass_mailer.UsersFilter'),
        ),
    ]
