# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import mass_mailer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass_mailer', '0002_auto_20200327_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='blacklist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='filters',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('0', 'Users w/o activations'), ('1', 'Users with payments'), ('2', 'Payments w/o activations')], max_length=12), blank=True, default=list, size=None),
        ),
    ]
