# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0002_auto_20200402_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
