# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0002_usersfilter_manual_email_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='ignore_subscriptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='send_once',
            field=models.BooleanField(default=True),
        ),
    ]
