# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0003_auto_20200327_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='messages_per_hour',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='messages_per_second',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='delay_between_connections',
            field=models.IntegerField(default=10, help_text='In seconds'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='messages_per_connection',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='blacklist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
