# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0004_auto_20200327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
    ]
