# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0004_auto_20200403_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='has_name_for_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='joined_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='joined_before',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='manual_blacklist',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='first_payment_was',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='last_payment_was',
            field=models.DateField(blank=True, null=True),
        ),
    ]
