# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0005_auto_20200411_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='send_only_first',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
