# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0006_usersfilter_send_only_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='do_not_send_to_pass_partout',
            field=models.BooleanField(default=False),
        ),
    ]
