# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0007_usersfilter_do_not_send_to_pass_partout'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='list_unsubscribe_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='do_not_send_to_gmail',
            field=models.BooleanField(default=False),
        ),
    ]
