# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import mass_mailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0008_auto_20200412_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfilter',
            name='filters',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('0', 'Users w/o activations'), ('1', 'Users with payments'), ('2', 'Payments w/o activations'), ('3', 'Users, which payed for 1 cup only'), ('4', 'Users, which payed for more than 1 cups')], max_length=12), blank=True, default=list, size=None),
        ),
    ]
