# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0009_auto_20200414_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='do_not_send_to_mailru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='do_not_send_to_yandex',
            field=models.BooleanField(default=False),
        ),
    ]
