# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0013_auto_20200514_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='send_to_not_validated',
            field=models.BooleanField(default=True),
        ),
    ]
