# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0014_usersfilter_send_to_not_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='last_activity_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='last_activity_before',
            field=models.DateField(blank=True, null=True),
        ),
    ]
