# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0015_auto_20211229_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_subject',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
