# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0020_auto_20230109_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('not_exist', 'Email not exist')], default='ok', max_length=16),
        ),
    ]
