# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-10 15:52
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0021_auto_20230109_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=annoying.fields.AutoOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
