# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-18 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass_mailer', '0022_auto_20230110_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='postman_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='postman_broadcast',
            field=models.BooleanField(default=False, help_text="Private messages for users, who, for some reason, can't or won't receive emails"),
        ),
        migrations.AddField(
            model_name='message',
            name='postman_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postmaster_broadcast_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='postman_subject',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
