# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0024_usersfilter_cups_amount_gte'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='result',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failure'), (3, "Didn't send"), (4, 'Success(P)')], default=3),
        ),
    ]
