# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0025_auto_20230125_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='min_lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
