# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0026_usersfilter_min_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='logged_more_than_once',
            field=models.BooleanField(default=True),
        ),
    ]
