# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-15 15:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0027_usersfilter_logged_more_than_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='last_activity_before',
            field=models.DateField(blank=True, help_text='Sessions Only', null=True),
        ),
    ]
