# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-17 14:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0029_usersfilter_payments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range_b',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_status_b',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('FORM_SHOWED', 'FORM_SHOWED'), ('DEADLINE_EXPIRED', 'DEADLINE_EXPIRED'), ('CANCELED', 'CANCELED'), ('PREAUTHORIZING', 'PREAUTHORIZING'), ('AUTHORIZING', 'AUTHORIZING'), ('AUTHORIZED', 'AUTHORIZED'), ('AUTH_FAIL', 'AUTH_FAIL'), ('REJECTED', 'REJECTED'), ('3DS_CHECKING', '3DS_CHECKING'), ('3DS_CHECKED', '3DS_CHECKED'), ('REVERSING', 'REVERSING'), ('PARTIAL_REVERSED', 'PARTIAL_REVERSED'), ('REVERSED', 'REVERSED'), ('CONFIRMING', 'CONFIRMING'), ('CONFIRMED', 'CONFIRMED'), ('REFUNDING', 'REFUNDING'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED'), ('REFUNDED', 'REFUNDED')], max_length=20, null=True),
        ),
    ]
