# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0030_auto_20230217_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='payments_exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_exclude_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range_days_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
