# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 13:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0031_auto_20230217_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='payments_exclude_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range_c',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='Bounds works as [,)', null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_range_days_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_status_c',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('FORM_SHOWED', 'FORM_SHOWED'), ('DEADLINE_EXPIRED', 'DEADLINE_EXPIRED'), ('CANCELED', 'CANCELED'), ('PREAUTHORIZING', 'PREAUTHORIZING'), ('AUTHORIZING', 'AUTHORIZING'), ('AUTHORIZED', 'AUTHORIZED'), ('AUTH_FAIL', 'AUTH_FAIL'), ('REJECTED', 'REJECTED'), ('3DS_CHECKING', '3DS_CHECKING'), ('3DS_CHECKED', '3DS_CHECKED'), ('REVERSING', 'REVERSING'), ('PARTIAL_REVERSED', 'PARTIAL_REVERSED'), ('REVERSED', 'REVERSED'), ('CONFIRMING', 'CONFIRMING'), ('CONFIRMED', 'CONFIRMED'), ('REFUNDING', 'REFUNDING'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED'), ('REFUNDED', 'REFUNDED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_statuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_statuses_b',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_statuses_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='payments_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='Bounds works as [,)', null=True),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='payments_range_b',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='Bounds works as [,)', null=True),
        ),
    ]
