# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import mass_mailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0032_auto_20230221_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfilter',
            name='payments_statuses',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(max_length=20), blank=True, choices=[('NEW', 'NEW'), ('FORM_SHOWED', 'FORM_SHOWED'), ('DEADLINE_EXPIRED', 'DEADLINE_EXPIRED'), ('CANCELED', 'CANCELED'), ('PREAUTHORIZING', 'PREAUTHORIZING'), ('AUTHORIZING', 'AUTHORIZING'), ('AUTHORIZED', 'AUTHORIZED'), ('AUTH_FAIL', 'AUTH_FAIL'), ('REJECTED', 'REJECTED'), ('3DS_CHECKING', '3DS_CHECKING'), ('3DS_CHECKED', '3DS_CHECKED'), ('REVERSING', 'REVERSING'), ('PARTIAL_REVERSED', 'PARTIAL_REVERSED'), ('REVERSED', 'REVERSED'), ('CONFIRMING', 'CONFIRMING'), ('CONFIRMED', 'CONFIRMED'), ('REFUNDING', 'REFUNDING'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED'), ('REFUNDED', 'REFUNDED')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='payments_statuses_b',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(max_length=20), blank=True, choices=[('NEW', 'NEW'), ('FORM_SHOWED', 'FORM_SHOWED'), ('DEADLINE_EXPIRED', 'DEADLINE_EXPIRED'), ('CANCELED', 'CANCELED'), ('PREAUTHORIZING', 'PREAUTHORIZING'), ('AUTHORIZING', 'AUTHORIZING'), ('AUTHORIZED', 'AUTHORIZED'), ('AUTH_FAIL', 'AUTH_FAIL'), ('REJECTED', 'REJECTED'), ('3DS_CHECKING', '3DS_CHECKING'), ('3DS_CHECKED', '3DS_CHECKED'), ('REVERSING', 'REVERSING'), ('PARTIAL_REVERSED', 'PARTIAL_REVERSED'), ('REVERSED', 'REVERSED'), ('CONFIRMING', 'CONFIRMING'), ('CONFIRMED', 'CONFIRMED'), ('REFUNDING', 'REFUNDING'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED'), ('REFUNDED', 'REFUNDED')], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='payments_statuses_c',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(max_length=20), blank=True, choices=[('NEW', 'NEW'), ('FORM_SHOWED', 'FORM_SHOWED'), ('DEADLINE_EXPIRED', 'DEADLINE_EXPIRED'), ('CANCELED', 'CANCELED'), ('PREAUTHORIZING', 'PREAUTHORIZING'), ('AUTHORIZING', 'AUTHORIZING'), ('AUTHORIZED', 'AUTHORIZED'), ('AUTH_FAIL', 'AUTH_FAIL'), ('REJECTED', 'REJECTED'), ('3DS_CHECKING', '3DS_CHECKING'), ('3DS_CHECKED', '3DS_CHECKED'), ('REVERSING', 'REVERSING'), ('PARTIAL_REVERSED', 'PARTIAL_REVERSED'), ('REVERSED', 'REVERSED'), ('CONFIRMING', 'CONFIRMING'), ('CONFIRMED', 'CONFIRMED'), ('REFUNDING', 'REFUNDING'), ('PARTIAL_REFUNDED', 'PARTIAL_REFUNDED'), ('REFUNDED', 'REFUNDED')], null=True, size=None),
        ),
    ]
