# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import mass_mailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0034_auto_20230221_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfilter',
            name='payments_category',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('coffee_cups', 'Чашки кофе'), ('tickets', 'Тикеты'), ('donations', 'Пожертвования')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_category_b',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('coffee_cups', 'Чашки кофе'), ('tickets', 'Тикеты'), ('donations', 'Пожертвования')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='payments_category_c',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('coffee_cups', 'Чашки кофе'), ('tickets', 'Тикеты'), ('donations', 'Пожертвования')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='recipient_country',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usersfilter',
            name='send_once_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
