# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import mass_mailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0035_auto_20230228_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='validate_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='recipient_country',
            field=mass_mailer.models.ChoiceArrayField(base_field=models.CharField(choices=[('RU', 'Russia'), ('FR', 'France'), ('UA', 'Ukraine'), ('BY', 'Belarus'), ('KZ', 'Kazakhstan'), ('DE', 'Germany'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('CA', 'Canada'), ('NL', 'Netherlands'), ('PL', 'Poland'), ('US', 'United States'), ('GB', 'United Kingdom'), ('ES', 'Spain'), ('IT', 'Italy'), ('UZ', 'Uzbekistan'), ('CZ', 'Czechia'), ('LV', 'Latvia'), ('AM', 'Armenia'), ('TR', 'Turkey'), ('MD', 'Moldova'), ('EE', 'Estonia'), ('IL', 'Israel'), ('LU', 'Luxembourg'), ('GE', 'Georgia'), ('LT', 'Lithuania'), ('KG', 'Kyrgyzstan'), ('AE', 'United Arab Emirates'), ('AZ', 'Azerbaijan'), ('FI', 'Finland'), ('BG', 'Bulgaria'), ('ME', 'Montenegro'), ('SE', 'Sweden'), ('IE', 'Ireland'), ('RS', 'Serbia'), ('RO', 'Romania'), ('TH', 'Thailand'), ('KR', 'South Korea'), ('AT', 'Austria'), ('IN', 'India'), ('TJ', 'Tajikistan'), ('BR', 'Brazil'), ('CY', 'Cyprus'), ('NO', 'Norway'), ('VN', 'Vietnam'), ('GN', 'Guinea'), ('DK', 'Denmark'), ('SK', 'Slovakia'), ('MA', 'Morocco'), ('CI', 'Ivory Coast'), ('NC', 'New Caledonia'), ('BJ', 'Benin'), ('TN', 'Tunisia'), ('CL', 'Chile'), ('AG', 'Antigua and Barbuda'), ('ID', 'Indonesia'), ('DZ', 'Algeria'), ('SG', 'Singapore'), ('LK', 'Sri Lanka'), ('ZA', 'South Africa'), ('PT', 'Portugal'), ('SC', 'Seychelles'), ('MC', 'Monaco'), ('HK', 'Hong Kong'), ('LA', 'Laos'), ('BH', 'Bahrain'), ('CD', 'DR Congo'), ('GR', 'Greece'), ('NG', 'Nigeria'), ('MN', 'Mongolia'), ('MY', 'Malaysia'), ('MX', 'Mexico'), ('MV', 'Maldives'), ('MU', 'Mauritius'), ('AU', 'Australia'), ('LB', 'Lebanon')], max_length=2), blank=True, null=True, size=None),
        ),
    ]
