# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-06 13:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0036_auto_20230404_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
    ]
