# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0037_message_bcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='backend',
            field=models.CharField(choices=[('django_ses.SESBackend', 'SESEmailBackend'), ('django.core.mail.backends.smtp.EmailBackend', 'SMTPEmailBackend')], default='django_ses.SESBackend', max_length=256),
        ),
    ]
