# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('click_url', models.URLField()),
                ('text_1st_bt', models.CharField(default=None, max_length=34, null=True)),
                ('text_2nd_bt', models.CharField(default=None, max_length=34, null=True)),
                ('url_1st_bt', models.URLField(default=None, null=True)),
                ('url_2nd_bt', models.URLField(default=None, null=True)),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('base64', models.BinaryField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_datetime', models.DateTimeField(default=None, null=True)),
                ('success', models.NullBooleanField(default=None)),
                ('error_description', models.CharField(default=None, max_length=300, null=True)),
                ('remote_id', models.CharField(default=None, max_length=16, null=True)),
                ('status', models.CharField(default=None, max_length=16, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationImage'),
        ),
    ]
