# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LK', 'Likes'), ('RP', 'Replyes')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
