# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190617_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LK', 'Likes'), ('RP', 'Replyes'), ('MG', 'Messages'), ('TP', 'Topics')], max_length=10, null=True),
        ),
    ]
