# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_auto_20190624_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='excpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
