# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-01 14:52
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0028_user_show_tickets'),
        ('notifications', '0006_notification_excpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckNotifications',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='check_notifications', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('has_new_notifications', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
