# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20191212_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
