# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 13:39
from __future__ import unicode_literals

import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('notifications', 'Notification')
    for row in MyModel.objects.all():
        row.key = uuid.uuid4()
        row.save(update_fields=['key'])

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_key'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
