# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20200121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   unique=True),
        ),
    ]
