# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20200121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='visit_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LK', 'Likes'), ('RP', 'Replies'), ('MG', 'Messages'), ('TP', 'Topics'), ('IR', 'Interval Repetitions')], max_length=10, null=True),
        ),
    ]
