# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-08 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0086_auto_20191028_2014'),
        ('polly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('demo', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_packets', to='home.LessonPage')),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('translation', models.CharField(max_length=120)),
                ('definition_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('repetition_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('cd_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Color Dictionary ID')),
                ('word', models.CharField(max_length=120, verbose_name='Word')),
                ('genre', models.CharField(blank=True, choices=[('f', 'Feminine'), ('m', 'Masculine'), ('m/f', 'Epicene'), ('m(f)', 'Both in one')], max_length=10, null=True, verbose_name='Gender')),
                ('part_of_speech', models.CharField(blank=True, choices=[('nom', 'Noun'), ('pron', 'Pronoun'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('conj', 'Conjunction'), ('verb', 'Verb'), ('prep', 'Preposition'), ('interj', 'Interjection'), ('loc', 'Locution'), ('phrase', 'Phrase'), ('partic', 'Partic')], max_length=10, null=True, verbose_name='Part of Speech')),
                ('plural', models.BooleanField(default=False, verbose_name='Plural')),
                ('grammatical_number', models.CharField(blank=True, choices=[('s', 'Singular'), ('pl', 'Plural'), ('s/pl', 'Singular + Plural'), ('col', 'Collective')], max_length=4, null=True)),
                ('definition_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=10, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=120)),
                ('packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet')),
                ('polly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='le_francais_dictionary.WordGroup'),
        ),
        migrations.AddField(
            model_name='word',
            name='packet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet'),
        ),
        migrations.AddField(
            model_name='word',
            name='packets',
            field=models.ManyToManyField(default=None, null=True, related_name='words', through='le_francais_dictionary.WordPacket', to='le_francais_dictionary.Packet'),
        ),
        migrations.AddField(
            model_name='word',
            name='polly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask'),
        ),
        migrations.AddField(
            model_name='userwordrepetition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
        migrations.AddField(
            model_name='userwordignore',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
        migrations.AddField(
            model_name='userworddata',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='le_francais_dictionary.Word'),
        ),
        migrations.AddField(
            model_name='unifiedword',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.WordGroup'),
        ),
        migrations.AddField(
            model_name='example',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
    ]
