# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0083_auto_20190827_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_packets', to='home.LessonPage')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(default=None)),
                ('stars', models.IntegerField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField()),
                ('mistakes', models.IntegerField()),
                ('user_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.UserWord')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_id', models.CharField(max_length=10, null=True, verbose_name='Color Dictionary ID')),
                ('word', models.CharField(max_length=120, verbose_name='Word')),
                ('genre', models.CharField(choices=[('f', 'Feminine'), ('m', 'Masculine'), ('m/f', 'Epicene'), ('m(f)', 'Both in one')], max_length=4, null=True, verbose_name='Gender')),
                ('part_of_speech', models.CharField(choices=[('nom', 'Noun'), ('pron', 'Pronoun'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('conj', 'Conjunction'), ('verb', 'Verb'), ('prep', 'Preposition'), ('interj', 'Interjection'), ('loc', 'Locution'), ('phrase', 'Phrase')], max_length=6, null=True, verbose_name='Part of Speech')),
                ('plural', models.BooleanField(default=False, verbose_name='Plural')),
                ('packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet')),
                ('polly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=120)),
                ('polly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word')),
            ],
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
        migrations.AddField(
            model_name='example',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
    ]
