# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='demo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
