# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('le_francais_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word')),
            ],
        ),
    ]
