# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition_num',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
