# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cd_id',
            field=models.IntegerField(null=True),
        ),
    ]
