# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0002_packet_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='packet',
        ),
        migrations.AlterField(
            model_name='packet',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordpacket',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet'),
        ),
        migrations.AddField(
            model_name='wordpacket',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='packets',
            field=models.ManyToManyField(default=None, null=True, related_name='words', through='le_francais_dictionary.WordPacket', to='le_francais_dictionary.Packet'),
        ),
    ]
