# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0002_word_cd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='genre',
            field=models.CharField(choices=[('f', 'Feminine'), ('m', 'Masculine')], max_length=1, null=True),
        ),
    ]
