# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0002_userwordrepetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordrepetition',
            name='repetition_date',
            field=models.DateField(null=True),
        ),
    ]
