# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0003_auto_20191108_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_ssml',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translations_ssml',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedword',
            name='definition_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
