# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0002_worduser_datetime'),
        ('le_francais_dictionary', '0003_auto_20190917_2013'),
    ]

    operations = [
    ]
