# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0003_auto_20191030_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='packet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet'),
        ),
    ]
