# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20190710_1552'),
        ('le_francais_dictionary', '0003_word_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lessons',
            field=models.ManyToManyField(null=True, related_name='dictionary_words', to='home.LessonPage'),
        ),
    ]
