# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('le_francais_dictionary', '0004_word_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='cd_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Color Dictionary ID'),
        ),
        migrations.AlterField(
            model_name='word',
            name='genre',
            field=models.CharField(blank=True, choices=[('f', 'Feminine'), ('m', 'Masculine'), ('m/f', 'Epicene'), ('m(f)', 'Both in one')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='word',
            name='packet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('nom', 'Noun'), ('pron', 'Pronoun'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('conj', 'Conjunction'), ('verb', 'Verb'), ('prep', 'Preposition'), ('interj', 'Interjection'), ('loc', 'Locution'), ('phrase', 'Phrase'), ('partic', 'Partic')], max_length=10, null=True, verbose_name='Part of Speech'),
        ),
        migrations.AlterField(
            model_name='word',
            name='polly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='polly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polly.PollyTask'),
        ),
        migrations.AddField(
            model_name='userwordignore',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Word'),
        ),
    ]
