# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-11 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0004_auto_20191111_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='_polly_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
