# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0005_word__polly_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtranslation',
            name='_polly_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
