# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0006_wordtranslation__polly_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedword',
            name='translation_polly_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unifiedword',
            name='word_polly_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
