# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0007_auto_20191114_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
