# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0008_word_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='_polly_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='le_francais_dictionary.WordGroup'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_ssml',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='_polly_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='translations_ssml',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
