# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0009_auto_20191115_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpacket',
            name='packet',
        ),
        migrations.RemoveField(
            model_name='wordpacket',
            name='word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='packets',
        ),
        migrations.DeleteModel(
            name='WordPacket',
        ),
    ]
