# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0010_auto_20191115_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordrepetition',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
