# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 17:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('le_francais_dictionary', '0010_auto_20191115_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStandalonePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packets', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
