# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0014_auto_20191125_2147'),
        ('le_francais_dictionary', '0011_auto_20191127_1732'),
    ]

    operations = [
    ]
