# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0015_merge_20191128_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_cards_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
