# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0016_auto_20191206_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userworddata',
            name='delay',
            field=models.IntegerField(null=True),
        ),
    ]
