# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0017_auto_20191213_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDayRepetition',
        ),
    ]
