# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 12:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('le_francais_dictionary', '0018_delete_userdayrepetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_qty', models.IntegerField(null=True)),
                ('words_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=1000)),
                ('date', models.DateField(null=True)),
                ('success', models.NullBooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
