# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 14:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0022_auto_20191216_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayrepetition',
            name='repetitions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=[], size=None),
        ),
    ]
