# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0001_initial'),
        ('le_francais_dictionary', '0025_userdayrepetition_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64, null=True)),
                ('audio_url', models.URLField(null=True)),
                ('translation_audio_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('form', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64)),
                ('audio_url', models.URLField(null=True)),
                ('translation_audio_url', models.URLField(null=True)),
                ('polly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_verb_form_set', to='polly.PollyTask')),
                ('translation_polly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_verb_form_translation_set', to='polly.PollyTask')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='VerbPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='verb',
            name='packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='le_francais_dictionary.VerbPacket'),
        ),
        migrations.AddField(
            model_name='verb',
            name='polly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_verb_set', to='polly.PollyTask'),
        ),
        migrations.AddField(
            model_name='verb',
            name='translation_polly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_verb_translation_set', to='polly.PollyTask'),
        ),
    ]
