# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0026_auto_20200114_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'ordering': ['lesson__lesson_number']},
        ),
        migrations.AlterModelOptions(
            name='verbform',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='verb',
            name='type',
            field=models.IntegerField(choices=[(0, 'affirmative'), (1, 'negative')], default=0),
        ),
        migrations.AddField(
            model_name='verbform',
            name='form_to_show',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verbform',
            name='is_shown',
            field=models.BooleanField(default=1),
        ),
    ]
