# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0026_auto_20200114_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'ordering': ['lesson__lesson_number']},
        ),
        migrations.AlterModelOptions(
            name='verbform',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='userstandalonepacket',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
