# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20191028_2014'),
        ('le_francais_dictionary', '0027_auto_20200205_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbpacket',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.LessonPage'),
        ),
    ]
