# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-25 11:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0029_auto_20200205_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstandalonepacket',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
