# Generated by Django 2.2.12 on 2020-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0030_userstandalonepacket_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='plural',
            field=models.BooleanField(blank=True, default=False, verbose_name='Plural'),
        ),
    ]
