# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0035_auto_20200909_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='tense',
            field=models.IntegerField(choices=[(0, 'Indicatif Présent'), (1, 'Passé Composé')], default=None, null=True),
        ),
    ]
