# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('le_francais_dictionary', '0037_auto_20201010_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='verbform',
            name='tense',
            field=models.IntegerField(choices=[(0, 'Indicatif Présent'), (1, 'Passé Composé'), (2, 'Impératif Présent'), (3, 'Imparfait'), (4, 'Futur Simple'), (4, 'Futur simple'), (5, 'Participe Passé')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='verbpacketrelation',
            name='tense',
            field=models.IntegerField(choices=[(0, 'Indicatif Présent'), (1, 'Passé Composé'), (2, 'Impératif Présent'), (3, 'Imparfait'), (4, 'Futur Simple'), (4, 'Futur simple'), (5, 'Participe Passé')], default=0),
        ),
    ]
