# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 11:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0038_auto_20210112_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayrepetition',
            name='repetitions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=[], size=None),
        ),
    ]
