# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0039_auto_20210112_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedword',
            name='translation_polly_url',
            field=models.URLField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedword',
            name='word_polly_url',
            field=models.URLField(default=None, max_length=300, null=True),
        ),
    ]
