# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0040_auto_20210114_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedword',
            name='translation_polly_url',
            field=models.URLField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedword',
            name='word_polly_url',
            field=models.URLField(default=None, max_length=1000, null=True),
        ),
    ]
