# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0041_auto_20210114_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworddata',
            name='custom_grade',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
