# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-10 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0043_userworddata_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packet',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_packets', to='home.LessonPage'),
        ),
        migrations.AlterField(
            model_name='userworddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_cards_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userworddata',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userdata', to='le_francais_dictionary.Word'),
        ),
        migrations.AlterField(
            model_name='userwordrepetition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='le_francais_dictionary.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='packet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='le_francais_dictionary.Packet'),
        ),
        migrations.AlterField(
            model_name='word',
            name='polly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polly.PollyTask'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='polly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polly.PollyTask'),
        ),
    ]
