# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0044_auto_20220210_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='word',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('nom', 'Noun'), ('pron', 'Pronoun'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('conj', 'Conjunction'), ('verb', 'Verb'), ('prep', 'Preposition'), ('interj', 'Interjection'), ('loc', 'Locution'), ('phrase', 'Phrase'), ('partic', 'Particle')], max_length=10, null=True, verbose_name='Part of Speech'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='le_francais_dictionary.Packet'),
        ),
    ]
