# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_speechkit', '0006_auto_20250131_1450'),
        ('le_francais_dictionary', '0045_auto_20221114_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='packet',
            name='cross_site_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packet',
            name='cross_site_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='cross_site_site_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='cross_site_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='cross_site_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='cross_site_site_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='voiceover_data_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='word_string',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation_string',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='voiceover_data_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='yandex_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='yandex_speechkit.YandexSpeechKitTask'),
        ),
        migrations.AlterField(
            model_name='word',
            name='cd_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Color Dictionary ID'),
        ),
        migrations.AddField(
            model_name='packet',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='le_francais_dictionary.Partner'),
        ),
    ]
