# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-28 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0046_auto_20250423_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='voiceover_data_changed',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='voiceover_data_changed',
        ),
    ]
