# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-09 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0046_auto_20250202_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='cross_site_id',
        ),
    ]
