# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0047_remove_word_cross_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cross_site_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
