# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0047_auto_20250428_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['packet__lesson__lesson_number', 'packet__id', 'order']},
        ),
        migrations.AddField(
            model_name='packet',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
