# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0048_word_cross_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='cd_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Color Dictionary ID'),
        ),
    ]
