# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-26 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0048_auto_20260126_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'ordering': ['order', 'lesson__lesson_number']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['packet__order', 'packet__lesson__lesson_number', 'order']},
        ),
    ]
