# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-14 18:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0049_auto_20260126_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstandalonepacket',
            name='filters_v2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
