# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-14 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0049_auto_20250210_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='voiceover_data_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='voiceover_data_changed',
            field=models.BooleanField(default=False),
        ),
    ]
