# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_francais_dictionary', '0050_auto_20250214_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
