# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-28 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('le_francais_dictionary', '0050_userstandalonepacket_filters_v2'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE le_francais_dictionary_userstandalonepacket
            SET filters_v2 = jsonb_set(COALESCE(filters_v2, '{}'::jsonb), '{main}', filters)
            WHERE filters IS NOT NULL;
            """,
            """
            UPDATE le_francais_dictionary_userstandalonepacket
            SET filters = filters_v2 -> 'main'
            WHERE filters_v2 IS NOT NULL
              AND filters_v2 -> 'main' IS NOT NULL;
            """
        )
    ]
